package com.creditsense.api;
import com.creditsense.domain.*; import com.creditsense.repo.Repositories; import com.creditsense.security.AccessPolicy; import com.creditsense.security.GoogleTokenVerifier; import com.creditsense.security.JwtService; import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.oauth2.jwt.JwtException; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.reactive.function.client.WebClient; import java.math.BigDecimal; import java.time.*; import java.util.*; import java.util.stream.Collectors;

@RestController @RequestMapping("/api") public class ApiController {
  private final Repositories.Users users; private final Repositories.Applicants applicants; private final Repositories.Applications applications; private final Repositories.Checks checks; private final Repositories.Assessments assessments; private final Repositories.Audits audits; private final PasswordEncoder passwords; private final JwtService tokens; private final ObjectMapper json; private final AccessPolicy policy; private final GoogleTokenVerifier google; private final JdbcTemplate jdbc;
  @Value("${ml.service-url}") private String mlUrl; @Value("${ml.api-key:}") private String mlKey;
  public ApiController(Repositories.Users users, Repositories.Applicants applicants, Repositories.Applications applications, Repositories.Checks checks, Repositories.Assessments assessments, Repositories.Audits audits, PasswordEncoder passwords, JwtService tokens, ObjectMapper json, AccessPolicy policy, GoogleTokenVerifier google, JdbcTemplate jdbc){this.users=users;this.applicants=applicants;this.applications=applications;this.checks=checks;this.assessments=assessments;this.audits=audits;this.passwords=passwords;this.tokens=tokens;this.json=json;this.policy=policy;this.google=google;this.jdbc=jdbc;}
  record AuthRequest(@Email String email,@Size(min=10) String password){} record RegisterRequest(@Email String email,@Size(min=10) String password){} record GoogleRequest(@NotBlank String credential){} record AuthResponse(String accessToken,String role,String email){}
  record ApplicationRequest(@NotBlank String businessName,@Pattern(regexp="[A-Z]{5}[0-9]{4}[A-Z]") String pan,@NotBlank String gstin,@NotBlank String address,@NotNull @DecimalMin("1") BigDecimal amountRequested,@NotBlank String purpose,@NotNull List<String> kycDocuments,@NotNull Map<String,Object> features,@AssertTrue(message="Consent is required") boolean consent){} record DecisionRequest(@NotNull AppStatus status,@NotBlank String reason){}

  // ---- authentication ----
  @GetMapping("/auth/options") public Map<String,Object> authOptions(){return Map.of("googleClientId",policy.googleClientId(),"passwordLogin",policy.passwordLoginEnabled());}
  @PostMapping("/auth/google") public AuthResponse googleLogin(@Valid @RequestBody GoogleRequest r){GoogleTokenVerifier.Identity who;try{who=google.verify(r.credential());}catch(JwtException e){throw new Unauthorized();}
    Role role=policy.roleFor(who.email()); User u=users.findByEmail(who.email()).orElse(null);
    if(u==null){u=users.save(new User(who.email(),passwords.encode(UUID.randomUUID().toString()),role));audit(u,"REGISTER_GOOGLE","USER",u.getId(),null,"{\"role\":\""+role+"\"}");}
    else if(u.getRole()!=role){String before=u.getRole().name();u.setRole(role);u=users.save(u);audit(u,"ROLE_SYNC","USER",u.getId(),"{\"role\":\""+before+"\"}","{\"role\":\""+role+"\"}");}
    return new AuthResponse(tokens.issue(u),u.getRole().name(),u.getEmail());}
  @PostMapping("/auth/register") public AuthResponse register(@Valid @RequestBody RegisterRequest r){ if(!policy.passwordLoginEnabled())throw new Forbidden(); if(users.findByEmail(r.email().toLowerCase()).isPresent())throw new BadRequest("Email already registered"); User u=users.save(new User(r.email().toLowerCase(),passwords.encode(r.password()),Role.APPLICANT)); audit(u,"REGISTER","USER",u.getId(),null,"{\"role\":\"APPLICANT\"}"); return new AuthResponse(tokens.issue(u),u.getRole().name(),u.getEmail()); }
  @PostMapping("/auth/login") public AuthResponse login(@Valid @RequestBody AuthRequest r){if(!policy.passwordLoginEnabled())throw new Forbidden();User u=users.findByEmail(r.email().toLowerCase()).orElseThrow(()->new Unauthorized());if(!passwords.matches(r.password(),u.getPasswordHash()))throw new Unauthorized();return new AuthResponse(tokens.issue(u),u.getRole().name(),u.getEmail());}

  // ---- applications ----
  /** Submit, run the compliance gate and (if it passes) the risk model in one call, so the applicant sees the outcome at once. An officer still makes the final decision. */
  @PostMapping("/applications") @PreAuthorize("hasRole('APPLICANT')") public Map<String,Object> submit(@Valid @RequestBody ApplicationRequest r,Authentication auth){User u=current(auth); Applicant a=applicants.findByUserId(u.getId()).orElseGet(Applicant::new); a.setUser(u);a.setBusinessName(r.businessName());a.setPan(r.pan());a.setGstin(r.gstin().toUpperCase());a.setAddress(r.address());a=applicants.save(a); LoanApplication app=new LoanApplication();app.setApplicant(a);app.setAmountRequested(r.amountRequested());app.setPurpose(r.purpose());app.setFeatureVector(jsonValue(r.features()));app.setKycDocuments(jsonValue(r.kycDocuments()));app.setConsentAt(Instant.now());applications.save(app); audit(u,"SUBMIT","APPLICATION",app.getId(),null,"{\"status\":\"SUBMITTED\"}");
    runCompliance(app,r.kycDocuments(),u); RiskAssessment risk=null; String message;
    if(app.getStatus()==AppStatus.COMPLIANCE_REVIEW){try{risk=runScoring(app,u);message="Compliance passed and the risk model has scored your application. A loan officer will make the final decision.";}catch(ServiceUnavailable e){message="Compliance passed, but the risk model is unavailable. Your application is in manual review.";}}else message="Your application did not pass the compliance checks, so it was not scored.";
    Map<String,Object> out=new LinkedHashMap<>();out.put("application",app);out.put("complianceChecks",checks.findByApplicationId(app.getId()));out.put("riskAssessment",risk);out.put("message",message);return out;}
  @PostMapping("/applications/{id}/compliance-check") @PreAuthorize("hasAnyRole('LOAN_OFFICER','ADMIN')") public Map<String,Object> compliance(@PathVariable UUID id,Authentication auth){LoanApplication app=ownedOrOfficer(id,current(auth));List<ComplianceCheck> result=runCompliance(app,storedDocs(app),current(auth));return Map.of("status",app.getStatus(),"checks",result);}
  @PostMapping("/applications/{id}/risk-assessment") @PreAuthorize("hasAnyRole('LOAN_OFFICER','ADMIN')") public RiskAssessment score(@PathVariable UUID id,Authentication auth){LoanApplication app=applications.findById(id).orElseThrow(NotFound::new);if(app.getStatus()!=AppStatus.COMPLIANCE_REVIEW)throw new BadRequest("Application must clear compliance before scoring");return runScoring(app,current(auth));}
  @PostMapping("/applications/{id}/decision") @PreAuthorize("hasAnyRole('LOAN_OFFICER','ADMIN')") public LoanApplication decide(@PathVariable UUID id,@Valid @RequestBody DecisionRequest r,Authentication auth){if(r.status()!=AppStatus.APPROVED&&r.status()!=AppStatus.REJECTED)throw new BadRequest("Decision must be APPROVED or REJECTED");LoanApplication app=applications.findById(id).orElseThrow(NotFound::new);if(app.getStatus()!=AppStatus.RISK_SCORED&&app.getStatus()!=AppStatus.MANUAL_REVIEW)throw new BadRequest("Application is not ready for a decision");String before=app.getStatus().name();app.setStatus(r.status());app.setDecisionReason(r.reason());app.setUpdatedAt(Instant.now());applications.save(app);audit(current(auth),"DECISION","APPLICATION",id,"{\"status\":\""+before+"\"}","{\"status\":\""+r.status()+"\"}");return app;}
  @GetMapping("/applications/{id}") public Map<String,Object> detail(@PathVariable UUID id,Authentication auth){LoanApplication a=ownedOrOfficer(id,current(auth));Map<String,Object> result=new LinkedHashMap<>();result.put("application",a);result.put("complianceChecks",checks.findByApplicationId(id));result.put("riskAssessment",assessments.findByApplicationId(id).orElse(null));return result;}
  @GetMapping("/applications/mine") @PreAuthorize("hasRole('APPLICANT')") public List<LoanApplication> mine(Authentication auth){return applications.findByApplicantUserId(current(auth).getId());}
  @GetMapping("/applications") @PreAuthorize("hasAnyRole('LOAN_OFFICER','ADMIN')") public List<LoanApplication> queue(@RequestParam(required=false) AppStatus status){return status==null?applications.findAll():applications.findAll().stream().filter(a->a.getStatus()==status).toList();}

  // ---- admin ----
  @GetMapping("/portfolio/analytics") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> analytics(){var all=applications.findAll();return Map.of("applications",all.size(),"statusDistribution",all.stream().collect(Collectors.groupingBy(a->a.getStatus().name(),Collectors.counting())),"riskDistribution",assessments.findAll().stream().collect(Collectors.groupingBy(RiskAssessment::getRiskBand,Collectors.counting())));}
  @GetMapping("/models/info") @PreAuthorize("hasRole('ADMIN')") public Map modelInfo(){return ml().get().uri("/model-info").retrieve().bodyToMono(Map.class).block(Duration.ofSeconds(5));}
  @PostMapping("/models/retrain") @PreAuthorize("hasRole('ADMIN')") public Map retrain(){return ml().post().uri("/retrain").retrieve().bodyToMono(Map.class).block(Duration.ofSeconds(60));}
  @GetMapping("/audit-logs") @PreAuthorize("hasRole('ADMIN')") public List<AuditLog> auditLogs(){return audits.findAll(org.springframework.data.domain.Sort.by(org.springframework.data.domain.Sort.Direction.DESC,"createdAt"));}

  // ---- privacy: let a person erase their own data ----
  @DeleteMapping("/me") @PreAuthorize("hasRole('APPLICANT')") @Transactional public Map<String,String> deleteMyData(Authentication auth){User u=current(auth);UUID id=u.getId();
    jdbc.update("DELETE FROM compliance_checks WHERE application_id IN (SELECT la.id FROM loan_applications la JOIN applicants ap ON ap.id=la.applicant_id WHERE ap.user_id=?)",id);
    jdbc.update("DELETE FROM risk_assessments WHERE application_id IN (SELECT la.id FROM loan_applications la JOIN applicants ap ON ap.id=la.applicant_id WHERE ap.user_id=?)",id);
    jdbc.update("DELETE FROM loan_applications WHERE applicant_id IN (SELECT id FROM applicants WHERE user_id=?)",id);
    jdbc.update("DELETE FROM applicants WHERE user_id=?",id);
    jdbc.update("UPDATE audit_logs SET actor_id=NULL WHERE actor_id=?",id);
    jdbc.update("DELETE FROM users WHERE id=?",id);
    jdbc.update("INSERT INTO audit_logs(id,actor_id,action,entity_type,entity_id) VALUES (?,NULL,'ACCOUNT_DELETED','USER',?)",UUID.randomUUID(),id);
    return Map.of("status","deleted");}

  // ---- internals ----
  private WebClient ml(){WebClient.Builder b=WebClient.builder().baseUrl(mlUrl);if(!mlKey.isBlank())b.defaultHeader("X-API-Key",mlKey);return b.build();}
  @SuppressWarnings("unchecked") private List<String> storedDocs(LoanApplication app){try{return json.readValue(app.getKycDocuments(),List.class);}catch(Exception e){return List.of();}}
  private List<ComplianceCheck> runCompliance(LoanApplication app,List<String> docs,User actor){UUID id=app.getId();checks.deleteByApplicationId(id);Applicant ap=app.getApplicant(); boolean gst=gstinValid(ap.getGstin()); boolean kyc=Set.of("PAN","UDYAM","ADDRESS_PROOF","BANK_STATEMENTS").stream().allMatch(docs::contains); boolean duplicate=applicants.findFirstByPan(ap.getPan()).filter(x->!x.getId().equals(ap.getId())).isPresent(); boolean velocity=applications.countByApplicantIdAndSubmittedAtAfter(ap.getId(),Instant.now().minus(Duration.ofDays(7)))>3; boolean address=ap.getAddress().trim().length()>8; boolean noFraud=!duplicate&&!velocity&&!ap.isBlacklisted()&&address; List<ComplianceCheck> result=List.of(new ComplianceCheck(app,"GST_VALIDITY",gst,gst?"Valid GSTIN checksum":"Invalid GSTIN checksum"),new ComplianceCheck(app,"KYC_COMPLETENESS",kyc,kyc?"All required documents supplied":"PAN, UDYAM, address proof and bank statements are required"),new ComplianceCheck(app,"FRAUD_FLAGS",noFraud,noFraud?"No fraud flags":"Duplicate PAN, velocity, blacklist or address mismatch detected"));checks.saveAll(result);app.setStatus(result.stream().allMatch(ComplianceCheck::isPassed)?AppStatus.COMPLIANCE_REVIEW:AppStatus.COMPLIANCE_FAILED);app.setUpdatedAt(Instant.now());applications.save(app);audit(actor,"COMPLIANCE_CHECK","APPLICATION",id,null,jsonValue(result));return result;}
  /** Calls the ML service; on any failure the application goes to MANUAL_REVIEW rather than being scored without an explanation. */
  private RiskAssessment runScoring(LoanApplication app,User actor){UUID id=app.getId();try{Map response=ml().post().uri("/predict").contentType(MediaType.APPLICATION_JSON).bodyValue(json.readValue(app.getFeatureVector(),Map.class)).retrieve().bodyToMono(Map.class).block(Duration.ofSeconds(20));if(response==null||response.get("explanation")==null)throw new IllegalStateException("ML explanation missing");RiskAssessment a=assessments.findByApplicationId(id).orElseGet(RiskAssessment::new);a.setApplication(app);a.setProbabilityOfDefault(new BigDecimal(response.get("probability_of_default").toString()));a.setRiskBand(response.get("risk_band").toString());a.setModelVersion(response.get("model_version").toString());a.setShapBreakdown(json.writeValueAsString(response.get("explanation")));a=assessments.save(a);app.setStatus(AppStatus.RISK_SCORED);app.setUpdatedAt(Instant.now());applications.save(app);audit(actor,"RISK_SCORED","APPLICATION",id,null,jsonValue(response));return a;}catch(Exception e){app.setStatus(AppStatus.MANUAL_REVIEW);app.setUpdatedAt(Instant.now());applications.save(app);audit(actor,"ML_UNAVAILABLE_MANUAL_REVIEW","APPLICATION",id,null,"{}");throw new ServiceUnavailable("ML scoring unavailable; application placed in manual review");}}
  private User current(Authentication a){return users.findById((UUID)a.getPrincipal()).orElseThrow(Unauthorized::new);} private LoanApplication ownedOrOfficer(UUID id,User u){LoanApplication a=applications.findById(id).orElseThrow(NotFound::new);if(u.getRole()==Role.APPLICANT&&!a.getApplicant().getUser().getId().equals(u.getId()))throw new Forbidden();return a;} private void audit(User u,String action,String type,UUID id,String before,String after){AuditLog l=new AuditLog();l.setActor(u);l.setAction(action);l.setEntityType(type);l.setEntityId(id);l.setBeforeState(before);l.setAfterState(after);audits.save(l);} private String jsonValue(Object x){try{return json.writeValueAsString(x);}catch(JsonProcessingException e){return "{}";}}
  static boolean gstinValid(String gst){if(gst==null||!gst.matches("[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]"))return false;String chars="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";int sum=0,factor=2;for(int i=13;i>=0;i--){int addend=chars.indexOf(gst.charAt(i))*factor;sum+=(addend/36)+(addend%36);factor=factor==2?1:2;}return chars.charAt((36-sum%36)%36)==gst.charAt(14);}
}
@RestControllerAdvice class Errors { @ExceptionHandler(BadRequest.class) ResponseEntity<Map<String,String>> bad(BadRequest e){return ResponseEntity.badRequest().body(Map.of("code","VALIDATION_ERROR","message",e.getMessage()));}@ExceptionHandler(org.springframework.web.bind.MethodArgumentNotValidException.class) ResponseEntity<Map<String,String>> invalid(org.springframework.web.bind.MethodArgumentNotValidException e){var f=e.getBindingResult().getFieldError();return ResponseEntity.badRequest().body(Map.of("code","VALIDATION_ERROR","message",f==null?"Invalid request":f.getField()+": "+f.getDefaultMessage()));}@ExceptionHandler(NotFound.class) ResponseEntity<Map<String,String>> no(NotFound e){return ResponseEntity.status(404).body(Map.of("code","NOT_FOUND","message","Resource not found"));}@ExceptionHandler({Unauthorized.class,Forbidden.class}) ResponseEntity<Map<String,String>> una(RuntimeException e){return ResponseEntity.status(e instanceof Forbidden?403:401).body(Map.of("code","ACCESS_DENIED","message","Access denied"));}@ExceptionHandler(ServiceUnavailable.class) ResponseEntity<Map<String,String>> unavailable(ServiceUnavailable e){return ResponseEntity.status(503).body(Map.of("code","ML_UNAVAILABLE","message",e.getMessage()));}}
class BadRequest extends RuntimeException{BadRequest(String m){super(m);}} class NotFound extends RuntimeException{} class Unauthorized extends RuntimeException{} class Forbidden extends RuntimeException{} class ServiceUnavailable extends RuntimeException{ServiceUnavailable(String m){super(m);}}
